- name: Install NodeJs
  hosts: all
  tasks:
    - name: Install Node
      shell: curl -fsSL https://deb.nodesource.com/setup_12.22.12.x | sudo -E bash -
      args:
        executable: /bin/bash
    - name: Install nodejs package
      become: true
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
        

