- name: Install NodeJs
  hosts: vm01
  tasks:
    - name: Install Node
      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      args:
        executable: /bin/bash
    - name: Install nodejs package
      become: true
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes